services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: koperasi_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - koperasi_network
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0
    container_name: koperasi_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: koperasi_db
      MYSQL_USER: koperasi_user
      MYSQL_PASSWORD: koperasi_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - koperasi_mysql_data:/var/lib/mysql
    networks:
      - koperasi_network

  node:
    image: node:20-alpine
    container_name: koperasi_node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host"
    networks:
      - koperasi_network

networks:
  koperasi_network:
    driver: bridge

volumes:
  koperasi_mysql_data:
    driver: local